# Generated by Django 3.1 on 2021-09-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userid',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilename',
            field=models.CharField(default='', max_length=20),
        ),
    ]
